In [30]:
import numpy as np
from numpy import genfromtxt #Used to generate an array from a text file

In [31]:
data = genfromtxt('bank_note_data.txt', delimiter=',') 
data
#A delimiter is a sequence of one or more characters used to specify the boundary between separate, independent regions in plain text 
#or other data streams. 
#An example of a delimiter is the comma character, which acts as a field delimiter in a sequence of comma-separated values.

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [32]:
#The last column, 0 or 1 indicates, whether or not it was an authentic note
#0 indicates a forgery note, 1 indicates, authentic

In [33]:
labels = data[:,4] #All the rows for last colum
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [59]:
features = data[:,0:4]
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [60]:
X = features
y = labels

#This is the general notation used in Machine learning

In [61]:
from sklearn.model_selection import train_test_split

In [62]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.33, random_state = 42)
#Basically, we are splitting the data into train and test. So, that we can train the model and test its performance

#Pass in X (features) and y (labels) 
#Choose your test size, 33% of the data is going ot go to the test set. So, 33% of the features will be in X_test, 33% of features will be in y_test
#random_state: This data (that was provided in the function call) is going to be shuffled before we actually split it into a test set and 
#training set. To make sure we get the same shuffle every time, we set teh randome_state. 42 is just an arbitrary value.

In [63]:
len(X_train)

919

In [64]:
len(X)

1372

In [65]:
0.33 * 1372

452.76000000000005

In [66]:
len(X_test)

453

In [67]:
#So 66.6% of data is now in X train. and 33.33% of data is now in X_test

In [68]:
len(y)

1372

In [69]:
len(y_train)

919

In [70]:
len(y_test)

453

In [84]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [85]:
X_test

array([[ 1.5691  ,  6.3465  , -0.1828  , -2.4099  ],
       [-0.27802 ,  8.1881  , -3.1338  , -2.5276  ],
       [ 0.051979,  7.0521  , -2.0541  , -3.1508  ],
       ...,
       [ 3.5127  ,  2.9073  ,  1.0579  ,  0.40774 ],
       [ 5.504   , 10.3671  , -4.413   , -4.0211  ],
       [-0.2062  ,  9.2207  , -3.7044  , -6.8103  ]])

In [86]:
y_train

array([1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 0.,
       1., 1., 1., 0., 1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0.,
       1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1.,
       1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1.,
       0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0.,
       1., 0., 0., 1., 0.

In [87]:
y_test

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1.,
       1., 0., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0.,
       0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       0., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1.,
       1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
       1., 1., 0., 1., 0.

In [71]:
from sklearn.preprocessing import MinMaxScaler #This will help us map the range of feature data to fall within a certain range
#This can help the neural network, to perform better

In [72]:
scaler_object = MinMaxScaler()

In [73]:
scaler_object.fit(X_train) #Finds the min and max value and the transform based on min and max. 

MinMaxScaler(copy=True, feature_range=(0, 1))

In [74]:
scaled_X_train = scaler_object.transform(X_train)

In [75]:
scaled_X_test = scaler_object.transform(X_test)

In [76]:
####Question: WHy did we only fit to X_train?
####Solution: We wanna make sure that this scalar object, doesnt get to peak at any test data. Otherwise, its kinda like cheating.
#Because, we are now gonna transform X_test having only fitted on X_train

In [77]:
scaled_X_train.max()

1.0000000000000002

In [88]:
X_train.max()

17.9274

In [79]:
scaled_X_train.min()

0.0

In [89]:
scaled_X_train

array([[4.44850688e-01, 5.14130449e-01, 2.18194638e-01, 8.50172258e-01],
       [6.53339968e-01, 5.82655745e-01, 9.93242398e-02, 8.17696322e-01],
       [4.81846700e-01, 6.69377018e-01, 3.61193167e-01, 7.63368407e-01],
       ...,
       [4.11050776e-04, 8.63104170e-01, 2.34046756e-01, 3.74261253e-01],
       [2.58284115e-01, 6.16029366e-01, 2.33861752e-01, 7.02643151e-01],
       [2.65661395e-01, 2.44444278e-01, 7.20316361e-01, 7.44775785e-01]])

In [80]:
from keras.models import Sequential
from keras.layers import Dense

In [81]:
model = Sequential()

model.add(Dense(4,input_dim = 4, activation = 'relu'))
#We have 4 neurons in this dense layer. The input dimension is 4 and the activation is rectified linear unit

model.add(Dense(8,activation = 'relu')) #we dont need to provide an input dimension because, this is not the input layer. This is the hidden layer.

model.add(Dense(1, activation = 'sigmoid')) #Because sigmoid function will be fit between 0 and 1


In [82]:
model.compile(loss = 'binary_crossentropy', optimizer = 'adam',metrics = ['accuracy'])

In [90]:
model.fit(scaled_X_train, y_train, epochs = 50, verbose = 2 )
#1 epoch means you've gone through all the training data one time
#Verbose is used to print along as it is training. 


Epoch 1/50
 - 1s - loss: 0.6891 - acc: 0.5462
Epoch 2/50
 - 0s - loss: 0.6816 - acc: 0.5495
Epoch 3/50
 - 0s - loss: 0.6763 - acc: 0.5495
Epoch 4/50
 - 0s - loss: 0.6716 - acc: 0.5495
Epoch 5/50
 - 0s - loss: 0.6664 - acc: 0.5495
Epoch 6/50
 - 0s - loss: 0.6606 - acc: 0.5495
Epoch 7/50
 - 0s - loss: 0.6526 - acc: 0.5495
Epoch 8/50
 - 0s - loss: 0.6429 - acc: 0.5495
Epoch 9/50
 - 0s - loss: 0.6316 - acc: 0.5778
Epoch 10/50
 - 0s - loss: 0.6181 - acc: 0.6366
Epoch 11/50
 - 0s - loss: 0.6018 - acc: 0.6453
Epoch 12/50
 - 0s - loss: 0.5844 - acc: 0.6801
Epoch 13/50
 - 0s - loss: 0.5661 - acc: 0.6964
Epoch 14/50
 - 0s - loss: 0.5470 - acc: 0.7160
Epoch 15/50
 - 0s - loss: 0.5281 - acc: 0.7508
Epoch 16/50
 - 0s - loss: 0.5082 - acc: 0.7661
Epoch 17/50
 - 0s - loss: 0.4894 - acc: 0.7998
Epoch 18/50
 - 0s - loss: 0.4694 - acc: 0.8292
Epoch 19/50
 - 0s - loss: 0.4510 - acc: 0.8390
Epoch 20/50
 - 0s - loss: 0.4329 - acc: 0.8585
Epoch 21/50
 - 0s - loss: 0.4156 - acc: 0.8596
Epoch 22/50
 - 0s - lo

In [91]:
#Now we have completed training. We need to go ahead with testing

In [93]:
model.predict_classes(scaled_X_test) #Used to perform prediction

array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    

In [94]:
#Now that we have predicted, we also need to evaluate how well our prediction was done 

In [95]:
model.metrics_names

['loss', 'acc']

In [96]:
from sklearn.metrics import confusion_matrix, classification_report

In [97]:
predictions = model.predict_classes(scaled_X_test)

In [98]:
#Now we have the predictions and right answers (in y_test)

In [99]:
confusion_matrix(y_test,predictions)

array([[254,   3],
       [  9, 187]], dtype=int64)

In [100]:
#As we can see it is only misidentifying 7 samples

In [101]:
print(classification_report(y_test, predictions))

             precision    recall  f1-score   support

        0.0       0.97      0.99      0.98       257
        1.0       0.98      0.95      0.97       196

avg / total       0.97      0.97      0.97       453



In [102]:
model.save('my_model.h5') #used to save the model

In [103]:
from keras.models import load_model

In [105]:
new_model = load_model('my_model.h5') #Load the saved model

In [106]:
new_model.predict_classes(scaled_X_test)

array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    